apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  namespace: app1
  labels:
    app: app1
spec:
  selector:
    matchLabels:
      app: app1
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: app1
        tier: frontend
    spec:
      containers:
      - image: wordpress:4.8-apache
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: db.db
        - name: WORDPRESS_DB_USER
          value: app1
        - name: WORDPRESS_DB_NAME
          value: db_app1
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: app1
        ports:
        - containerPort: 80
          name: app1
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: app1-pvc-claim
