apiVersion: v1
kind: Service
metadata:
  name: app1
  namespace: app1
  labels:
    app: app1
spec:
  ports:
    - port: 80
      nodePort: 30080
  selector:
    app: app1
    tier: frontend
  type: NodePort
