apiVersion: v1
kind: Service
metadata:
  name: app2
  namespace: app2
  labels:
    app: app2
spec:
  ports:
    - port: 80
      nodePort: 30081
  selector:
    app: app2
    tier: frontend
  type: NodePort
