apiVersion: v1
kind: Service
metadata:
  name: app3
  namespace: app3
  labels:
    app: app3
spec:
  ports:
    - port: 80
      nodePort: 30082
  selector:
    app: app3
    tier: frontend
  type: NodePort
