apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  ports:
    - port: 80
      nodePort: 30083
  selector:
    app: phpmyadmin
  type: NodePort
