apiVersion: v1
kind: PersistentVolume
metadata:
  name: app1-pv-volume
  labels:
    type: app1
spec:
  storageClassName: app1
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/sistema/app01"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app1-pvc-claim
  namespace: app1
spec:
  storageClassName: app1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
