apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv-volume
  labels:
    type: db
spec:
  storageClassName: db
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/sistema/bd01"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc-claim
  namespace: db
spec:
  storageClassName: db
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
